# Generated by Django 3.0.7 on 2020-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название места')),
                ('placeId', models.CharField(max_length=255, unique=True, verbose_name='уникальный идентификатор')),
                ('detailsUrl', models.URLField(verbose_name='ссылка на детальные данные')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
            ],
        ),
    ]
