# Generated by Django 3.0.7 on 2020-11-15 17:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('places', '0001_initial'), ('places', '0002_image'), ('places', '0003_auto_20200613_1446'), ('places', '0004_remove_place_detailsurl'), ('places', '0005_auto_20200613_1854'), ('places', '0006_auto_20201115_1720'), ('places', '0007_auto_20201115_1724'), ('places', '0008_auto_20201115_1732')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название места')),
                ('place_id', models.CharField(max_length=255, unique=True, verbose_name='уникальный идентификатор')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('long_description', tinymce.models.HTMLField(blank=True, verbose_name='полное описание')),
                ('short_description', models.TextField(blank=True, verbose_name='краткое описание')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'локации',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок отображения картинки')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.Place', verbose_name='место, к которому относится картинка')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
