# Generated by Django 3.0.7 on 2020-12-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_squashed_0008_auto_20201115_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
