# Generated by Django 3.0.7 on 2020-06-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(default=' ', verbose_name='полное описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.TextField(default='text', verbose_name='краткое описание'),
            preserve_default=False,
        ),
    ]
