# Generated by Django 3.0.7 on 2020-11-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200613_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'локация', 'verbose_name_plural': 'локации'},
        ),
    ]
